baseURL = 'blog.kalilarosa.xyz'
languageCode = 'en-us'
title = 'Yet another trashy dev blog'
# URL handling
relativeURLs = true
canonifyURLs = true
pygmentsUseClasses = true

# Performance optimizations
enableRobotsTXT = true
enableGitInfo = true
minify = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

[minify.tdewolff.html]
  keepDefaultAttrVals = false
  keepDocumentTags = true
  keepEndTags = true
  keepQuotes = false
  keepWhitespace = false

[caches]
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = '10m'
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = '10m'
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = '720h'
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = '720h'

[params]
name = "Adam Kalinowski"
location = "St. Petersburg, FL, USA"
description = "Just a silly little guy"
profile_image = "/images/profile.jpg"
github = "https://github.com/adamkali"
email = "adam.kalilarosa@proton.me"
linkedin = "https://linkedin.com/in/yourusername"
copyright="Adam Kalinowski"

# Taxonomy configuration
[taxonomies]
category = "categories"
tag = "tags"

### Personal Information

[params.socialIcons]
github = "https://github.com/adamkali"
email = "adam.kalilarosa@proton.me"
linkedin = "https://linkedin.com/in/yourusername"

### Experience Section

[[params.experience]]
company = "Legal Automation Systems"
role = "Fullstack Software Engineer"
period = "October 2021 - Present"
logo = "/images/company/logo.png"
description = "Brief description of your role and responsibilities."
responsibilities = [
    "Responsibility 1 with specific achievements",
    "Responsibility 2 with specific achievements",
    "Responsibility 3 with specific achievements"
]

# Navigation
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
title = "/"
url = "/"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Posts"
title = "posts"
url = "/posts"
weight = 2
[[menu.main]]
identifier = "configs"
name = "Configs"
title = "Configs"
url = "/configs"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about"
weight = 4
[[menu.main]]
identifier = "github"
name = "Github"
title = "GitHub"
url = "https://github.com/adamkali"
weight = 5
[[menu.main]]
identifier = "linkedin"
name = "Linkedin"
title = "linkedin"
url = "www.linkedin.com/in/adam-kalinowski-a8209a1b1"
weight = 6
[[menu.main]]
identifier = "rss"
name = "RSS"
title = "RSS Feed"
url = "/index.xml"
weight = 7

# Front matter configuration for Neorg compatibility
[frontmatter]
date = ['created', 'date', 'publishDate', 'lastmod']
lastmod = ['updated', 'lastmod', 'modified']
publishDate = ['created', 'date', 'publishDate']

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'
