baseURL = 'blog.kalilarosa.xyz'
languageCode = 'en-us'
theme = "not-much"
title = 'Jus a silly little blog.'
# URL handling
relativeURLs = true
canonifyURLs = true

[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
name = "Adam Kalinowski"
location = "St. Petersburg, FL, USA"
description = "Just a silly little guy"
profile_image = "/images/profile.jpg"
github = "https://github.com/adamkali"
email = "adam.kalilarosa@proton.me"
linkedin = "https://linkedin.com/in/yourusername"

# Taxonomy configuration
[taxonomies]
category = "categories"
tag = "tags"

### Personal Information

[params.socialIcons]
github = "https://github.com/adamkali"
email = "adam.kalilarosa@proton.me"
linkedin = "https://linkedin.com/in/yourusername"

### Experience Section

[[params.experience]]
company = "Legal Automation Systems"
role = "Fullstack Software Engineer"
period = "October 2021 - Present"
logo = "/images/company/logo.png"
description = "Brief description of your role and responsibilities."
responsibilities = [
    "Responsibility 1 with specific achievements",
    "Responsibility 2 with specific achievements",
    "Responsibility 3 with specific achievements"
]
[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Navigation
[menu]
[[menu.main]]
identifier = "home"
name = "home"
title = "/"
url = "/"
weight = 1
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/posts"
weight = 2
[[menu.main]]
identifier = "about"
name = "about"
title = "About"
url = "/about"
weight = 3
[[menu.main]]
identifier = "github"
name = "github"
title = "GitHub"
url = "https://github.com/imgios/not-much"
weight = 4
