# The schema 

"$schema" = 'https://starship.rs/config-schema.json'

# Now for the format

format = '''
$os $directory $git_branch$git_commit 
$rust$python$lua$golang$gleam$dotnet$bun$character '''

# Colors

palette = 'vaporlush'
[palettes.vaporlush]
bg = '#0e102d'
fg = '#079ef0'
bg_highlight = '#0a2846'
fg_highlight = '#5885ed'
comment = '#8da0b8'
primary0 = '#0700de'
primary1 = '#0b03fc'
primary2 = '#352ff5'
primary3 = '#4e47ff'
secondary0 = '#b50465'
secondary1 = '#e60580'
secondary2 = '#fa34a1'
secondary3 = '#fc65b8'
tertiary0 = '#3f10cc'
tertiary1 = '#6439e6'
tertiary2 = '#8864f5'
tertiary3 = '#af95fc'
quartary0 = '#fc5e03'
quartary1 = '#fc853f'
quartary2 = '#f59b67'
quartary3 = '#ffb68c'

# Code

[bun]
symbol = ' '
style = 'bold bg:#aaaacc fg:bg_highlight'
format = '[ $symbol $version ]($style)'

# Character 

[character] # The name of the module we are configuring is 'character'
success_symbol = '[ॐ ](bold quartary3)'
error_symbol = '[ॐ ](bold quartary0)'
vimcmd_symbol = '[](bold primary2)'
vimcmd_replace_one_symbol = '[](bold secondary2)'
vimcmd_replace_symbol = '[](bold secondary0)'
vimcmd_visual_symbol = '[](bold tertiary2)'

# Docker Context

[docker_context]
symbol = ' '
style = 'bold primary1'
format = '[ $symbol $version ]($style)'

# Git Branch

[git_branch]
symbol = ' '
truncation_length = 8
truncation_symbol = ''
ignore_branches = ['master', 'main']

# Git Commit

[git_commit]
commit_hash_length = 4
tag_symbol = '󰓹 '

# Gleam

[gleam]
symbol = ' '
style = 'bold tertiary1'
format = '[ $symbol $version ]($style)'

# Go

[golang]
symbol = ''
style = 'bold primary3'
format = '[ $symbol $version ]($style)'

# Lua

[lua]
symbol = ' '
style = 'bold primary0'
format = '[ $symbol $version ]($style)'

# Node

[nodejs]
symbol = ' '
style = 'bold #00ccaa'
format = '[ $symbol $version ]($style)'

# OS

[os]
disabled = false
style = "quartary0"
[os.symbols]
Ubuntu = " "
Arch = " "
Windows = " "
Macos = " "

# Rust 

[rust]
symbol = ' '
style = 'bold #c71e26'
format = '[ $symbol $version ]($style)'

# Python

[python]
symbol = ' '
pyenv_version_name = true
style = 'bold quartary1'
format = '[ $symbol $version ]($style)'
